version: "3"
services:
  dev-tanos-api:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command: "celery -A modules.adapter.infrastructure.celery.crawler_queue.crawler_celery worker -B --loglevel=info -P threads -c 1"
    logging:
      driver: awslogs
      options:
        # FIX : Change log group
        awslogs-group: toadhome/dev-antgirl-api-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/dev-antgirl-api-logs
        awslogs-create-group: "true"
    environment:
    # Environment