version: "3"
services:
  dev-tanos-api:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command: "newrelic-admin run-program gunicorn --timeout 30 -w 2 --threads 2 -k gevent -b :8000 --access-logfile - --error-logfile - application:app"
    logging:
      driver: awslogs
      options:
        # FIX : Change log group
        awslogs-group: toadhome/dev-antgirl-api-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/dev-antgirl-api-logs
        awslogs-create-group: "true"
    environment:
    # Environment