version: "3"
services:
  dev-antgirl-cron:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command: "celery -A modules.adapter.infrastructure.celery.crawler_queue.crawler_celery beat -l info --auto-interval=10"
    logging:
      driver: awslogs
      options:
        awslogs-group: toadhome/dev-antgirl-cron-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/dev-antgirl-cron-logs
        awslogs-create-group: "true"
    environment:
      # environment