version: "3"
services:
  dev-antgirl-api:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command: "celery -A modules.adapter.infrastructure.celery.crawler_queue.crawler_celery beat --loglevel=info --max-interval 10"
    logging:
      driver: awslogs
      options:
        # FIX : Change log group
        awslogs-group: toadhome/dev-antgirl-api-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/dev-antgirl-api-logs
        awslogs-create-group: "true"
    environment:
    # Environment

  dev-antgirl-crawler:
    image: __ECR_ADDRESS__
      command: "celery -A modules.adapter.infrastructure.celery.crawler_queue.crawler_celery worker --loglevel=info --queues=crawler"
      logging:
        driver: awslogs
        options:
          # FIX : Change log group
          awslogs-group: toadhome/dev-antgirl-api-logs
          awslogs-region: ap-northeast-2
          awslogs-stream-prefix: toadhome/dev-antgirl-api-logs
          awslogs-create-group: "true"
      environment:
      # Environment

  dev-antgirl-etl:
    image: __ECR_ADDRESS__
      command: "celery -A modules.adapter.infrastructure.celery.etl_queue.etl_celery worker --loglevel=info --queues=etl"
      logging:
        driver: awslogs
        options:
          # FIX : Change log group
          awslogs-group: toadhome/dev-antgirl-api-logs
          awslogs-region: ap-northeast-2
          awslogs-stream-prefix: toadhome/dev-antgirl-api-logs
          awslogs-create-group: "true"
      environment:
      # Environment