version: "3"
services:
  dev-antgirl-api:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command: "supervisord -c supervisord.conf"
    logging:
      driver: awslogs
      options:
        # FIX : Change log groupa
        awslogs-group: toadhome/dev-antgirl-api-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/dev-antgirl-api-logs
        awslogs-create-group: "true"
    environment:
    # Environment
