version: "3"
services:
  dev-antgirl-cron:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command: "celery -A modules.adapter.infrastructure.celery.etl_queue.etl_celery worker -B --loglevel=info -P threads -c 1"
    logging:
      driver: awslogs
      options:
        awslogs-group: toadhome/dev-antgirl-cron-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/dev-antgirl-cron-logs
        awslogs-create-group: "true"
    environment:
      # environment