version: "3"
services:
  prod-antgirl-cron:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
    command:  "celery -A modules.adapter.infrastructure.celery.crawler_queue.crawler_celery beat"
    logging:
      driver: awslogs
      options:
        awslogs-group: toadhome/prod-antgirl-cron-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/prod-antgirl-cron-logs
        awslogs-create-group: "true"
    environment:
      # environment