version: "3"
services:
  prod-antgirl-api:
    image: __ECR_ADDRESS__
    ports:
      - "8000:8000"
      - "9001:9001"
    command: "supervisord -c supervisord.conf"
    logging:
      driver: awslogs
      options:
        # FIX : Change log group
        awslogs-group: toadhome/prod-antgirl-api-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: toadhome/prod-antgirl-api-logs
        awslogs-create-group: "true"
    environment:
    # Environment