from sqlalchemy import Column, String, BigInteger, Integer, Text, Float

from modules.adapter.infrastructure.sqlalchemy.mapper import datalake_base
from modules.adapter.infrastructure.sqlalchemy.persistence.model.mixins.timestamp_mixin import (
    TimestampMixin,
)


class SubscriptionInfoModel(datalake_base, TimestampMixin):
    __tablename__ = "subscription_infos"

    id = Column(
        BigInteger().with_variant(Integer, "sqlite"), nullable=False, primary_key=True, autoincrement=True
    )
    subs_id = Column(
        BigInteger().with_variant(Integer, "sqlite"), nullable=False, index=True
    )
    offer_date = Column(String(10), nullable=True)
    notice_winner_date = Column(String(10), nullable=True)
    name = Column(String(100), nullable=True)
    area_type = Column(String(10), nullable=True)
    supply_price = Column(String(10), nullable=True)
    second_subs_amount = Column(String(20), nullable=True)
    origin_address = Column(String(250), nullable=True)
    new_address = Column(String(250), nullable=True)
    supply_household = Column(String(10), nullable=True)
    offer_notice_url = Column(Text, nullable=True)
    move_in_date = Column(String(10), nullable=True)
    contract_date = Column(String(23), nullable=True)
    hompage_url = Column(Text, nullable=True)
    special_supply_date = Column(String(25), nullable=True)
    special_supply_etc_date = Column(String(25), nullable=True)
    special_etc_gyeonggi_date = Column(String(25), nullable=True)
    first_supply_date = Column(String(25), nullable=True)
    first_supply_etc_date = Column(String(25), nullable=True)
    first_etc_gyeonggi_date = Column(String(25), nullable=True)
    second_supply_date = Column(String(25), nullable=True)
    second_supply_etc_date = Column(String(25), nullable=True)
    second_etc_gyeonggi_date = Column(String(25), nullable=True)
    supply_area = Column(Float, nullable=True)
    region = Column(String(2), nullable=True)
    housing_category = Column(String(2), nullable=True)
    rent_type = Column(String(10), nullable=True)
    construct_company = Column(String(50), nullable=True)
    contact = Column(String(25), nullable=True)
    subscription_date = Column(String(23), nullable=True)
    special_supply_status = Column(String(6), nullable=True)
    cmptt_rank = Column(String(6), nullable=True)
    special_household = Column(String(6), nullable=True)
    multi_children_vol_etc_gyeonggi = Column(String(10), nullable=True)
    multi_children_vol_etc = Column(String(10), nullable=True)
    multi_children_household = Column(String(10), nullable=True)
    multi_children_vol = Column(String(10), nullable=True)
    newlywed_vol_etc_gyeonggi = Column(String(10), nullable=True)
    newlywed_vol_etc = Column(String(10), nullable=True)
    newlywed_household = Column(String(10), nullable=True)
    newlywed_vol = Column(String(10), nullable=True)
    first_life_vol_etc_gyeonggi = Column(String(10), nullable=True)
    first_life_vol_etc = Column(String(10), nullable=True)
    first_life_household = Column(String(10), nullable=True)
    first_life_vol = Column(String(10), nullable=True)
    old_parent_vol_etc_gyeonggi = Column(String(10), nullable=True)
    old_parent_vol_etc = Column(String(10), nullable=True)
    old_parent_household = Column(String(10), nullable=True)
    old_parent_vol = Column(String(10), nullable=True)
    agency_recommend_etc_gyeonggi = Column(String(10), nullable=True)
    agency_recommend_etc = Column(String(10), nullable=True)
    agency_recommend_house_hold = Column(String(10), nullable=True)
    agency_recommend_vol = Column(String(10), nullable=True)
    official_general_household = Column(String(10), nullable=True)
    general_household = Column(String(10), nullable=True)
    first_accept_cnt = Column(String(10), nullable=True)
    first_accept_cnt_gyeonggi = Column(String(10), nullable=True)
    first_accept_cnt_etc = Column(String(10), nullable=True)
    second_accept_cnt = Column(String(10), nullable=True)
    second_accept_cnt_gyeonggi = Column(String(10), nullable=True)
    second_accept_cnt_etc = Column(String(10), nullable=True)
    first_cmptt_rate = Column(String(10), nullable=True)
    first_cmptt_rate_gyeonggi = Column(String(10), nullable=True)
    first_cmptt_rate_etc = Column(String(10), nullable=True)
    second_cmptt_rate = Column(String(10), nullable=True)
    second_cmptt_rate_gyeonggi = Column(String(10), nullable=True)
    second_cmptt_rate_etc = Column(String(10), nullable=True)
    lowest_win_point = Column(String(10), nullable=True)
    lowest_win_point_gyeonggi = Column(String(10), nullable=True)
    lowest_win_point_etc = Column(String(10), nullable=True)
    top_win_point = Column(String(10), nullable=True)
    top_win_point_gyeonggi = Column(String(10), nullable=True)
    top_win_point_etc = Column(String(10), nullable=True)
    avg_win_point = Column(String(10), nullable=True)
    avg_win_point_gyeonggi = Column(String(10), nullable=True)
    avg_win_point_etc = Column(String(10), nullable=True)
